### ISSUE TITLE
Map or list as terraform.Apply argument

### ISSUE THREAD

**Issue by sergibarroso** [hashicorp/terraform-exec#236]
Hi terraform-exec team,

I've got a noob question that popped up while testing terraform-exec with my actual code.

I'm actually using terraform apply by:

```
[...]

instanceName = "test-server"
tf.Apply(ctx, tfexec.Var(instanceName))

[...]
```

I also wanted to send some tags, but `tfexec.Var` only allows strings, is there any recommended way to pass maps or lists to `Apply`?

```
[...]

instanceName = "test-server"
instanceTags = maps[string]string{
  "owner": "XYZ",
  "env": "testing",
}
tf.Apply(ctx, tfexec.Var(instanceName), tfexec.Var(instanceTags))

[...]
```

Thanks in advance 👍🏻

**Comment by radeksimko** [comment]
Hi @sergibarroso 
The interpretation of the variable value passed through a `var` flag depends on the variable type constraints set by the module you're applying, i.e. the `type` attribute of `variable`, e.g.

```hcl
variable "primitive" {
  type = bool
}
variable "complex" {
  type = list(string)
}
```
Variables of primitive types can be passed directly, such as `-var=primitive=true` and complex ones are treated as expressions, which comes at the cost of some escaping, e.g. `-var=complex="[\"one\", \"two\"]"`. Escaping is also one of the reasons that there is no "consistent" behaviour for the interpretation of that flag as if there was it means that you'd also always need to put double quotes around strings.

So while you can pass complex variable values as `tfexec.Var`, it may not be most convenient. I would recommend you to consider generating `tfvars` files on the fly and passing them via `-var-file=path` ([`tfexec.VarFile`](https://pkg.go.dev/github.com/hashicorp/terraform-exec@v0.15.0/tfexec#VarFile)). Variable files also support JSON format, which seems like a format more suitable for this kind of use case in automation. This means you can avoid having to generate HCL.

You could generate these files on-the-fly in a temporary file `anything.tfvars.json` and dispose of them after the run is finished. Just be aware that you may end up storing the variable values (which may be sensitive) on a filesystem. This may be fine, but it depends on where you execute these Terraform runs and how isolated the environment is, i.e. who/what else might access that file in a that location. This is to say that you should not treat the file any differently to a state file, if it was on a filesystem.

If you do however decide to generate HCL - maybe because the variables are in fact passed as a human input - then you may find some of these libraries useful:

 - https://pkg.go.dev/github.com/zclconf/go-cty/cty/gocty#ImpliedType
 - https://pkg.go.dev/github.com/zclconf/go-cty/cty/gocty#ToCtyValue
 - https://pkg.go.dev/github.com/hashicorp/hcl/v2/hclwrite#TokensForValue

At that point you would just continue using the `Var` option, just pass a generated and escaped string - you can do most of the escaping via `fmt.Sprintf("%q")` I assume, but there may be some OS differences to deal with.

This page also provides further details on the interpretation of `-var` flag: https://www.terraform.io/docs/cli/commands/plan.html#input-variables-on-the-command-line

--- 

Does this answer your question?

**Comment by sergibarroso** [comment]
Thanks @radeksimko that was exactly it.

So I guess I will have to generate a `tfexec.VarFile`

**Comment by shazib-summar** [comment]
Hello @sergibarroso @radeksimko, I'm facing a similar issue. I would like to generate a `[]tfexec.VarOptions` on the fly to provide to Apply and Destroy functions. I would prefer not to use a tfvars file because of the overhead of creating/deleting the files. 

I use the following function to obtain `[]tfexec.VarOptions` from a `map[string]string`
```go
func getTFvarsFromMap(vars map[string]string) []tfexec.VarOption {
	var tfVars []tfexec.VarOption
	for k, v := range vars {
		tfVars = append(tfVars, *tfexec.Var(k + "=" + v))
	}
	return tfVars
}
```

and the following wrapper for tf.Apply()
```go
func tfApply(tf *tfexec.Terraform, vars map[string]string) error {
	tfVars := getTFvarsFromMap(vars)
	err := tf.Apply(context.Background(),
		tfVars...,
	)
	return errors.Wrap(err, "tf.Apply")
}
```
However, I get an `IncompatibleAssign` error: "cannot use tfVars (variable of type []tfexec.VarOption) as []tfexec.ApplyOption value in argument to tf.Apply" 

Im very confused by this. tfexec.VarOption [implements the ApplyOption interface](https://github.com/hashicorp/terraform-exec/blob/bd36395afaf34daf3c535e39d0aaf5fe52fbbebb/tfexec/apply.go#L85), so why is go complaining here? I am a noob and would really appreciate any help.
