### ISSUE TITLE
Consider removing exported error types

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-exec#296]
The tfexec exported error types - for example, [`tfexec.ErrCLIUsage`](https://pkg.go.dev/github.com/hashicorp/terraform-exec/tfexec#ErrCLIUsage) and [`tfexec.ErrTFVersionMismatch`](https://github.com/hashicorp/terraform-exec/blob/v0.16.1/tfexec/exit_errors.go#L279) - are implemented by parsing Terraform's human-readable error output using regular expressions.

Since this log output is subject to frequent changes and not covered by the [v1.0 compatibility promises](https://www.terraform.io/language/v1-compatibility-promises), users of these error types are at risk of having their code broken by new Terraform versions, requiring them (in the best case) to keep terraform-exec updated.

This error parsing code also seems to be a leading cause of terraform-exec nightly test failures.

Are these error types useful enough to consumers to continue maintaining them? Should we remove them prior to v1.0.0? Are there any really good use cases?

**Comment by bflad** [comment]
To gain some insight on potential usage in the wild, I spent some time with GitHub's code search (fuzzy matching on `tfexec.{TYPE}` because it'd be difficult to ignore non-tfexec things and most Go code doesn't use aliasing), e.g.

| Error Type | External GitHub Repo Usage | Code Search URL |
|---|---|---|
| `ErrConfigInvalid` | 1 | https://cs.github.com/?scopeName=All+repos&scope=&q=language%3Ago+%22tfexec.ErrConfigInvalid%22 |
| `ErrLockIdInvalid` | 0 | https://cs.github.com/?scopeName=All+repos&scope=&q=language%3Ago+%22tfexec.ErrLockIdInvalid%22 |
| `ErrMissingVar ` | 2 | https://cs.github.com/?scopeName=All+repos&scope=&q=language%3Ago+%22tfexec.ErrMissingVar%22  |
| `ErrNoConfig ` | 1 | https://cs.github.com/?scopeName=All+repos&scope=&q=language%3Ago+%22tfexec.ErrNoConfig%22 |
| `ErrNoInit ` | 1 | https://cs.github.com/?scopeName=All+repos&scope=&q=language%3Ago+%22tfexec.ErrNoInit%22 |
| `ErrNoWorkspace ` | 3 | https://cs.github.com/?scopeName=All+repos&scope=&q=language%3Ago+%22tfexec.ErrNoWorkspace%22 |
| `ErrStateLocked ` | 1 | https://cs.github.com/?scopeName=All+repos&scope=&q=language%3Ago+%22tfexec.ErrStateLocked%22 |
| `ErrStatePlanRead ` | 0 | https://cs.github.com/?scopeName=All+repos&scope=&q=language%3Ago+%22tfexec.ErrStatePlanRead%22 |
| `ErrTFVersionMismatch ` | 0 | https://cs.github.com/?scopeName=All+repos&scope=&q=language%3Ago+%22tfexec.ErrTFVersionMismatch%22 |
| `ErrWorkspaceExists ` | 2 | https://cs.github.com/?scopeName=All+repos&scope=&q=language%3Ago+%22tfexec.ErrWorkspaceExists%22 |

What I found was:

- https://github.com/hashicorp/consul-terraform-sync (`ErrNoWorkspace` / `ErrWorkspaceExists`)
- https://github.com/ministryofjustice/cloud-platform-cli (`ErrNoWorkspace` / `ErrWorkspaceExists`)
- https://github.com/weaveworks/tf-controller (`ErrStateLocked`)
- https://github.com/nunchistudio/temporal-land/tree/main/integrations/terraform
- https://github.com/CoverGo/terraform-wrapper (really just a terraform-exec fork)

I personally think that these removals are okay given the maintenance burden.
